In [1]:
import cv2
import numpy as np
from skimage.measure import compare_ssim, compare_psnr
import imutils
import matplotlib.pyplot as plt

%matplotlib inline

In [ ]:
# this should work with PIL Image, didn't use it the first time but when this cell is uncommented -> comment two cell below
# import glob
# from PIL import Image
# images = glob.glob('images/*.jpg')
# img = Image.open(picture)

In [2]:
# comment this cell if code above is used
# reading into files
img_to_rsz1 = cv2.imread('./images/Hurricane_Harvey_TX_before.jpg')
img_to_rsz2 = cv2.imread('./images/Hurricane_Harvey_TX_after.jpg')
img_to_rsz3 = cv2.imread('./images/Hurricane_Harvey_freeport_before.jpg')
img_to_rsz4 = cv2.imread('./images/Hurricane_Harvey_freeport_after.jpg')
img_to_rsz5 = cv2.imread('./images/Tornado_Joplin_Missouri_before.jpg')
img_to_rsz6 = cv2.imread('./images/Tornado_Joplin_Missouri_after.jpg')
img_to_rsz7 = cv2.imread('./images/wildfire_CA_before.jpg')
img_to_rsz8 = cv2.imread('./images/Wildfire_CA_wildfire_after.jpg')
img_to_rsz9 = cv2.imread('./images/omaha_before.jpg')
img_to_rsz10 = cv2.imread('./images/omaha_after.jpg')

In [3]:
# comment this cell if code above is used
images = [img_to_rsz1, img_to_rsz2, img_to_rsz3, img_to_rsz4, img_to_rsz5,
          img_to_rsz6, img_to_rsz7, img_to_rsz8, img_to_rsz9, img_to_rsz10]

In [4]:
# print out the image shape
for img in images:
    print(img.shape)

(421, 560, 3)
(419, 559, 3)
(594, 809, 3)
(596, 797, 3)
(791, 542, 3)
(795, 618, 3)
(370, 745, 3)
(390, 743, 3)
(480, 720, 3)
(480, 720, 3)


In [5]:
# cropping images
cropped = []
for i, img in enumerate(images):
    if img.shape[0] in range(350,400) and img.shape[1] in range(700,800):
        cropped.append(img[5:350, 5:700])
    elif img.shape[0] in range(400,450) and img.shape[1] in range(500,600):
        cropped.append(img[5:400, 5:500])
    elif img.shape[0] in range(450,500) and img.shape in range(700,750):
        cropped.append(img[5:450, 5:700])
    elif img.shape[0] in range(550,600) and img.shape[1] in range(750,850):
        cropped.append(img[5:550, 5:750])
    elif img.shape[0] in range(750,800) and img.shape[1] in range(500,650):
        cropped.append(img[5:750, 5:550])
    else:
        print(f'check image sizes of {img[i]}')
 

check image sizes of [[101 157 192]
 [ 92 127 160]
 [ 93 130 168]
 ...
 [ 62  88 135]
 [ 63  88 128]
 [ 67  91 143]]
check image sizes of [[ 85 112 103]
 [ 81 113 112]
 [100 140 145]
 ...
 [ 96 148 131]
 [ 98 144 132]
 [ 88 125 121]]


In [6]:
# check the cropped image sizes
for img in cropped:
    print(img.shape)

(395, 495, 3)
(395, 495, 3)
(545, 745, 3)
(545, 745, 3)
(745, 537, 3)
(745, 545, 3)
(345, 695, 3)
(345, 695, 3)


In [7]:
# write the files
for i, img in enumerate(cropped):
    cv2.imwrite(f'./Outputimages/cropped{i}.jpg', img)

In [8]:
# convert images to grayscale
gray = []
for img in cropped:
    gray.append(cv2.cvtColor(img, cv2.COLOR_BGR2GRAY))

In [9]:
# write the files
for i, img in enumerate(gray):
    cv2.imwrite(f'./Grayimages/grayscaled{i}.jpg', img)

In [10]:
# calculating the ssim score (Structural Similarity Index)
for i, img in enumerate(gray):
    if i < len(gray) and i%2==0:
        (score, diff) = compare_ssim(img[i], img[i+1], full=True)
        diff = (diff * 255).astype("uint8")
        print(f'SSIM for {i} pair is: {score}')
        print(f'PSNR for {i} pair is: {compare_psnr(img[i], img[i+1])}')

SSIM for 0 pair is: 0.6092987811343469
PSNR for 0 pair is: 20.656434413614605
SSIM for 2 pair is: 0.5045837860622617
PSNR for 2 pair is: 19.9518504701099
SSIM for 4 pair is: 0.6485553949588426
PSNR for 4 pair is: 18.588252711788744
SSIM for 6 pair is: 0.3277414819575182
PSNR for 6 pair is: 16.198003704135512
